import { Link, Navigate } from "react-router-dom";
import { ArrowLeft, Minus, Plus, ShoppingBag as BagIcon, Trash2 } from "lucide-react";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import { Button } from "@/components/ui/button";
import { useStore, formatPrice } from "@/context/StoreContext";

const ShoppingBag = () => {
  const { cart, setQuantity, products, productPrices, authLoading, paymentSettings } = useStore();
  const lines = cart.flatMap((line) => {
    const product = products.find((item) => item.slug === line.slug);
    const price = productPrices[line.slug];
    return product && price !== undefined ? [{ ...line, product, price }] : [];
  });
  const subtotal = lines.reduce((sum, line) => sum + line.price * line.quantity, 0);
  if (authLoading) return <div className="min-h-screen bg-background"><Header /><main className="mx-auto max-w-6xl px-5 py-20 text-muted-foreground">Loading your bag…</main><Footer /></div>;
  if (!lines.length && cart.length) return <div className="min-h-screen bg-background"><Header /><main className="mx-auto max-w-6xl px-5 py-20"><h1 className="font-display text-4xl font-extrabold">Bag</h1><p className="mt-4 text-muted-foreground">Some products are unavailable right now. Remove them to continue.</p>{cart.map((line) => <div key={line.slug} className="flex items-center justify-between border-b border-border py-5"><span className="font-semibold">{line.slug.split("-").join(" ")}</span><Button variant="outline" onClick={() => setQuantity(line.slug, 0)}>Remove</Button></div>)}<Button asChild className="mt-6"><Link to="/#shop">Continue shopping</Link></Button></main><Footer /></div>;
  return <div className="min-h-screen bg-background"><Header /><main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 lg:py-16"><Link to="/#shop" className="inline-flex items-center gap-2 text-sm font-bold"><ArrowLeft className="h-4 w-4" /> Continue shopping</Link><h1 className="mt-6 font-display text-4xl font-extrabold">Your bag <span className="text-muted-foreground">({lines.reduce((sum, line) => sum + line.quantity, 0)})</span></h1>
    {lines.length ? <div className="mt-8 grid gap-10 lg:grid-cols-[1fr_340px]"><div className="divide-y divide-border border-y border-border">{lines.map(({ slug, quantity, product, price }) => <article key={slug} className="grid grid-cols-[88px_1fr_auto] gap-4 py-5 sm:grid-cols-[112px_1fr_auto] sm:gap-6"><Link to={`/products/${slug}`} className="aspect-square overflow-hidden bg-secondary"><img src={product.image} alt={product.name} className="h-full w-full object-cover" /></Link><div className="flex flex-col justify-between"><div><Link to={`/products/${slug}`} className="font-display text-lg font-extrabold">{product.name}</Link><p className="mt-1 text-sm text-muted-foreground">{product.tagline}</p><p className="mt-2 font-bold">{formatPrice(price)}</p></div><div className="mt-4 inline-flex w-fit items-center border border-border"><Button variant="ghost" size="icon" aria-label={`Decrease ${product.name} quantity`} onClick={() => setQuantity(slug, quantity - 1)}><Minus className="h-4 w-4" /></Button><span className="w-9 text-center text-sm font-bold">{quantity}</span><Button variant="ghost" size="icon" aria-label={`Increase ${product.name} quantity`} onClick={() => setQuantity(slug, quantity + 1)}><Plus className="h-4 w-4" /></Button></div></div><div className="flex flex-col items-end justify-between"><p className="font-bold">{formatPrice(price * quantity)}</p><Button variant="ghost" size="icon" aria-label={`Remove ${product.name}`} onClick={() => setQuantity(slug, 0)}><Trash2 className="h-4 w-4" /></Button></div></article>)}</div>
    <aside className="h-fit border-y border-border py-6 lg:border lg:p-6"><h2 className="font-display text-xl font-extrabold">Order summary</h2><div className="mt-5 flex justify-between text-sm"><span>Subtotal</span><span>{formatPrice(subtotal)}</span></div><p className="mt-2 text-sm text-muted-foreground">Delivery fee {paymentSettings?.shipping_paise != null ? formatPrice(paymentSettings.shipping_paise) : "shown at checkout"}.</p><Button asChild className="mt-6 h-12 w-full font-bold"><Link to="/checkout">Continue to checkout</Link></Button><p className="mt-4 text-center text-xs text-muted-foreground">UPI or bank transfer · No cash on delivery</p></aside></div> : <div className="border-y border-border py-16 text-center"><BagIcon className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-4 font-display text-2xl font-extrabold">Your bag is empty</h2><p className="mt-2 text-muted-foreground">Find the serum that fits your daily ritual.</p><Button asChild className="mt-6"><Link to="/#shop">Explore serums</Link></Button></div>}
  </main><Footer /></div>;
};

export default ShoppingBag;